/**
 * Market — show-record summarization for market listings (Wave 3).
 *
 * "The horse's record is the product": these helpers turn raw
 * show_records rows into the compact competitive-record line a buyer
 * sees on a market card, and rank full records "best first" for the
 * quick-look dialog. Pure, no I/O — the batched fetch lives in
 * buildShowRingCards (src/app/actions/showring.ts) and
 * getPublicMarketHorseRecord (src/app/actions/marketPublicRecord.ts).
 *
 * Vocabulary notes (see src/lib/shows/placings.ts + ShowRecordTimeline):
 *  - v2 engine writes placings "1st"…"6th" and championship rows whose
 *    placing contains "Champion" ("Grand Champion", "Section Champion"…).
 *  - Legacy self-reported rows are free text: "1st", "2", "Top Ten",
 *    "NAN Champion" — and sometimes carry the champion signal in
 *    ribbon_color instead ("Grand Champion" ribbon).
 *  - verification_tier: 'platform_generated' (🛡️ MHH) and
 *    'host_verified' (✅) count as verified; 'self_reported'/null do not.
 */

/** The minimal show_records columns the summary needs. */
export interface RecordSummaryInputRow {
    horse_id: string | null;
    placing: string | null;
    ribbon_color: string | null;
    verification_tier: string | null;
}

/** Compact competitive record for one horse (market-card chip data). */
export interface HorseRecordSummary {
    /** All show-record rows (placings + championships + participation). */
    total: number;
    /** Placed results that are not championships ("1st", "Top Ten", …). */
    placings: number;
    /** Champion / Reserve Champion rows, any scope. */
    championships: number;
    /** Rows verified by the platform or a show host (never self-reported). */
    verified: number;
}

const VERIFIED_TIERS: readonly string[] = ["platform_generated", "host_verified"];

const CHAMPION_RE = /champion/i;

/**
 * A championship row: the placing says so, or (legacy rows) the ribbon
 * does — the old trophy case stored "Grand Champion" as a ribbon color.
 */
export function isChampionshipRecord(
    placing: string | null,
    ribbonColor: string | null,
): boolean {
    return CHAMPION_RE.test(placing ?? "") || CHAMPION_RE.test(ribbonColor ?? "");
}

/** Verified = generated by the MHH engine or confirmed by a show host. */
export function isVerifiedTier(tier: string | null): boolean {
    return tier !== null && VERIFIED_TIERS.includes(tier);
}

/**
 * Aggregate raw show_records rows (one batched query for the whole
 * page of listings) into per-horse summaries. Horses with no rows are
 * simply absent from the map — the card renders nothing for them
 * (empty-state honesty: never "0 placings").
 */
export function summarizeShowRecords(
    rows: RecordSummaryInputRow[],
): Map<string, HorseRecordSummary> {
    const byHorse = new Map<string, HorseRecordSummary>();
    for (const row of rows) {
        if (!row.horse_id) continue;
        let summary = byHorse.get(row.horse_id);
        if (!summary) {
            summary = { total: 0, placings: 0, championships: 0, verified: 0 };
            byHorse.set(row.horse_id, summary);
        }
        summary.total += 1;
        if (isChampionshipRecord(row.placing, row.ribbon_color)) {
            summary.championships += 1;
        } else if ((row.placing ?? "").trim().length > 0) {
            summary.placings += 1;
        }
        if (isVerifiedTier(row.verification_tier)) {
            summary.verified += 1;
        }
    }
    return byHorse;
}

/**
 * The compact chip text: "3 placings · 1 championship". Championships
 * and placings only appear when non-zero; a horse whose rows are all
 * participation still gets an honest "2 show records". Returns null
 * when there is nothing to say (no chip, no noise).
 */
export function recordChipLabel(summary: HorseRecordSummary | null | undefined): string | null {
    if (!summary || summary.total <= 0) return null;
    const parts: string[] = [];
    if (summary.placings > 0) {
        parts.push(`${summary.placings} placing${summary.placings === 1 ? "" : "s"}`);
    }
    if (summary.championships > 0) {
        parts.push(`${summary.championships} championship${summary.championships === 1 ? "" : "s"}`);
    }
    if (parts.length === 0) {
        parts.push(`${summary.total} show record${summary.total === 1 ? "" : "s"}`);
    }
    return parts.join(" · ");
}

/**
 * Verification-tier suffix for the chip: "verified" when every record
 * is platform/host verified, "2 verified" for a mix, null when none
 * are (self-reported records still count — they just claim no
 * authority they don't have).
 */
export function verifiedChipLabel(summary: HorseRecordSummary | null | undefined): string | null {
    if (!summary || summary.verified <= 0) return null;
    if (summary.verified >= summary.total) return "verified";
    return `${summary.verified} verified`;
}

// ── Best-first ranking (quick-look dialog, ≤5 rows) ──

const GRAND_RE = /grand/i;
const RESERVE_RE = /reserve/i;

/**
 * Lower is better. Grand Champion 0 · Reserve Grand 1 · Champion 2 ·
 * Reserve Champion 3 · "1st"… → 10+n · other placed text ("Top Ten")
 * 90 · participation/null 100.
 */
export function recordRank(placing: string | null): number {
    const text = (placing ?? "").trim();
    if (text.length === 0) return 100;
    if (CHAMPION_RE.test(text)) {
        const reserve = RESERVE_RE.test(text);
        if (GRAND_RE.test(text)) return reserve ? 1 : 0;
        return reserve ? 3 : 2;
    }
    const digits = text.match(/^(\d+)/);
    if (digits) {
        const n = parseInt(digits[1], 10);
        if (Number.isFinite(n) && n > 0) return 10 + Math.min(n, 79);
    }
    return 90;
}

export interface RankableRecord {
    placing: string | null;
    /** ISO date (or null) — recency is the tiebreak within a rank. */
    showDate: string | null;
}

/**
 * One row of the market quick-look dialog (view model returned by
 * getPublicMarketHorseRecord in src/app/actions/marketPublicRecord.ts
 * — typed here because "use server" files may only export async
 * functions).
 */
export interface MarketRecordDetailRow extends RankableRecord {
    id: string;
    showName: string;
    showId: string | null;
    showDateText: string | null;
    className: string | null;
    division: string | null;
    ribbonColor: string | null;
    verificationTier: string | null;
    isNan: boolean;
}

/**
 * Best result first; within the same rank, most recent first (undated
 * rows last). Returns a new array — input order is the final tiebreak
 * (Array#sort is stable).
 */
export function sortRecordsBestFirst<T extends RankableRecord>(records: T[]): T[] {
    return [...records].sort((a, b) => {
        const rankDiff = recordRank(a.placing) - recordRank(b.placing);
        if (rankDiff !== 0) return rankDiff;
        if (a.showDate === b.showDate) return 0;
        if (a.showDate === null) return 1;
        if (b.showDate === null) return -1;
        return a.showDate < b.showDate ? 1 : -1;
    });
}
