"use client";

/**
 * Market listings — the record chip + quick-look dialog (Wave 3).
 *
 * "The horse's record is the product": a listed horse with a
 * competitive record shows a compact 🏆 chip on its market card
 * (data batched server-side — see buildShowRingCards). Clicking the
 * chip opens a quick-look dialog fetched ON DEMAND for that one horse
 * (getMarketHorseRecord): best results first, verification tiers, MHH
 * card count, and the road to the full trophy case on the public
 * passport. Horses without records render nothing — never "0
 * placings".
 */

import { useState } from "react";
import Link from "next/link";

import { getMarketHorseRecord, type MarketHorseRecord } from "@/app/actions/market";
import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import {
    isChampionshipRecord,
    recordChipLabel,
    verifiedChipLabel,
    type HorseRecordSummary,
    type MarketRecordDetailRow,
} from "@/lib/market/recordSummary";

/** Same fuzzy-date preference as ShowRecordTimeline. */
function formatShowDate(dateStr: string | null, dateText: string | null): string | null {
    if (dateText && (!dateStr || dateStr.endsWith("-01-01"))) return dateText;
    if (!dateStr) return null;
    return new Date(dateStr + "T00:00:00").toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
    });
}

function TierBadge({ tier, isNan }: { tier: string | null; isNan: boolean }) {
    if (tier === "platform_generated") {
        return (
            <span
                className="inline-flex items-center gap-[2px] rounded-sm bg-success/15 px-1.5 py-[1px] text-[0.65rem] font-bold text-success"
                title="Record generated by MHH competition engine"
            >
                🛡️ MHH
            </span>
        );
    }
    if (tier === "host_verified") {
        return (
            <span
                className="inline-flex items-center gap-[2px] rounded-sm bg-info/15 px-1.5 py-[1px] text-[0.65rem] font-bold text-info"
                title="Verified by show host or judge"
            >
                ✅ Host
            </span>
        );
    }
    if (isNan) return null; // legacy NAN rows carry their own ⭐ badge
    return (
        <span
            className="inline-flex items-center gap-[2px] rounded-sm bg-muted px-1.5 py-[1px] text-[0.65rem] font-medium text-muted-foreground"
            title="Self-reported by collector"
        >
            📝 Self
        </span>
    );
}

function RecordRow({ record }: { record: MarketRecordDetailRow }) {
    const champion = isChampionshipRecord(record.placing, record.ribbonColor);
    const date = formatShowDate(record.showDate, record.showDateText);
    return (
        <li className="rounded-md bg-muted px-3 py-2">
            <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
                <span className={champion ? "font-serif font-bold text-warning" : "font-semibold text-foreground"}>
                    {champion ? "🏆 " : "🎖️ "}
                    {record.placing || "Shown"}
                </span>
                {record.isNan && (
                    <span className="inline-flex items-center gap-[2px] rounded-sm bg-warning/15 px-1.5 py-[1px] text-[0.65rem] font-bold tracking-wider text-warning uppercase">
                        ⭐ NAN
                    </span>
                )}
                <TierBadge tier={record.verificationTier} isNan={record.isNan} />
            </div>
            <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-0.5 text-xs text-secondary-foreground">
                {record.className && <span>{record.className}</span>}
                <span>
                    {record.showId ? (
                        <Link
                            href={`/shows/${record.showId}`}
                            className="text-forest no-underline hover:underline"
                        >
                            {record.showName}
                        </Link>
                    ) : (
                        record.showName
                    )}
                </span>
                {date && <span>· {date}</span>}
            </div>
        </li>
    );
}

export default function HorseRecordChip({
    horseId,
    horseName,
    summary,
}: {
    horseId: string;
    horseName: string;
    summary: HorseRecordSummary;
}) {
    const [open, setOpen] = useState(false);
    const [record, setRecord] = useState<MarketHorseRecord | null>(null);
    const [state, setState] = useState<"idle" | "loading" | "error" | "loaded">("idle");

    const chipLabel = recordChipLabel(summary);
    const verifiedLabel = verifiedChipLabel(summary);
    // Empty-state honesty: no record, no chip, no noise.
    if (!chipLabel) return null;

    const handleOpenChange = async (next: boolean) => {
        setOpen(next);
        if (!next || state === "loaded" || state === "loading") return;
        setState("loading");
        try {
            const result = await getMarketHorseRecord({ horseId });
            if (result.success) {
                setRecord(result.record);
                setState("loaded");
            } else {
                setState("error");
            }
        } catch {
            setState("error");
        }
    };

    return (
        <Dialog open={open} onOpenChange={handleOpenChange}>
            <DialogTrigger asChild>
                <button
                    type="button"
                    className="inline-flex max-w-full cursor-pointer items-center gap-1 rounded-full border border-warning/50 bg-warning/10 px-2 py-0.5 text-[0.7rem] font-semibold text-warning transition-colors hover:bg-warning/20"
                    title="View show record"
                    id={`record-chip-${horseId}`}
                >
                    <span aria-hidden="true">🏆</span>
                    <span className="truncate">{chipLabel}</span>
                    {verifiedLabel && (
                        <span className="font-medium text-warning/90">· ✅ {verifiedLabel}</span>
                    )}
                </button>
            </DialogTrigger>
            <DialogContent>
                <DialogHeader>
                    <DialogTitle className="font-serif text-lg">
                        🏆 {horseName} — Show Record
                    </DialogTitle>
                    <DialogDescription>
                        Competitive record on Model Horse Hub. Records follow the horse when it
                        changes hands.
                    </DialogDescription>
                </DialogHeader>

                {state === "loading" && (
                    <div className="space-y-2">
                        <Skeleton className="h-12 w-full" />
                        <Skeleton className="h-12 w-full" />
                        <Skeleton className="h-12 w-3/4" />
                    </div>
                )}

                {state === "error" && (
                    <p className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
                        Could not load the show record. Try again in a moment.
                    </p>
                )}

                {state === "loaded" && record && (
                    <>
                        <div className="flex flex-wrap items-center gap-2 text-sm text-secondary-foreground">
                            <span className="font-semibold text-foreground">
                                {recordChipLabel(record.summary) ?? "No show records yet"}
                            </span>
                            {verifiedChipLabel(record.summary) && (
                                <span className="inline-flex items-center gap-1 rounded-sm bg-success/15 px-2 py-[1px] text-xs font-bold text-success">
                                    ✅ {verifiedChipLabel(record.summary)}
                                </span>
                            )}
                        </div>

                        {record.topRecords.length > 0 && (
                            <ul className="m-0 list-none space-y-2 p-0">
                                {record.topRecords.map((row) => (
                                    <RecordRow key={row.id} record={row} />
                                ))}
                            </ul>
                        )}

                        {(record.summary?.total ?? 0) > record.topRecords.length && (
                            <p className="text-xs text-muted-foreground italic">
                                Best {record.topRecords.length} of {record.summary?.total} results
                                shown.
                            </p>
                        )}

                        {record.cardCount > 0 && (
                            <p className="rounded-md bg-warning/10 px-3 py-2 text-sm text-foreground">
                                🎖️{" "}
                                <span className="font-semibold">
                                    {record.cardCount} MHH qualification card
                                    {record.cardCount === 1 ? "" : "s"}
                                </span>{" "}
                                — live cards transfer with the horse.
                            </p>
                        )}
                    </>
                )}

                <DialogFooter>
                    <Button asChild variant="outline">
                        <Link href={`/community/${horseId}`} className="no-underline">
                            View full trophy case →
                        </Link>
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
