import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(__dirname, '../src');
const REPORT_PATH = path.join(__dirname, '../.agents/workflows/ui-hitlist-update.md');

const BANNED_PATTERNS = [
  { regex: /bg-\[rgba\(/g, name: 'Legacy RGBA Backgrounds' },
  { regex: /border-\[rgba\(/g, name: 'Legacy RGBA Borders' },
  { regex: /\bborder-edge\b/g, name: 'Legacy "border-edge" class' },
  { regex: /\bbg-glass\b/g, name: 'Legacy "bg-glass" class' },
  { regex: /\bbg-card\b/g, name: 'Legacy "bg-card" class' },
  { regex: /style=\{\{.*?(padding|margin|display|align|justify|gap).*?\}\}/gi, name: 'Inline Layout Styles' },
  { regex: /max-w-\[var\(--max-width\)/g, name: 'Legacy Max-Width Container' }
];

let totalIssues = 0;
let markdownReport = '# 🕵️ UI/UX Audit Hit List\n\n> This file was auto-generated by the Recon Agent. Check off items as they are fixed in the Burn-Down phase.\n\n';
let pagesWithoutLayouts = [];
let componentViolations = [];

function walkDir(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      walkDir(fullPath);
    } else if (fullPath.endsWith('.tsx') || fullPath.endsWith('.ts')) {
      checkFile(fullPath);
    }
  }
}

function checkFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const relativePath = path.relative(path.join(__dirname, '..'), filePath);
  let fileIssues = [];
  let fileHasIssues = false;

  // 1. Check for missing Layout Wrappers in pages
  if (relativePath.includes('\\app\\') && relativePath.endsWith('page.tsx')) {
    const hasLayout = /ExplorerLayout|ScrapbookLayout|CommandCenterLayout|FocusLayout/.test(content);
    // Ignore layout.tsx, error.tsx, loading.tsx, etc.
    if (!hasLayout && !relativePath.includes('api\\') && !relativePath.includes('layout.tsx') && !relativePath.includes('not-found.tsx') && !relativePath.includes('error.tsx')) {
      pagesWithoutLayouts.push(relativePath);
      fileHasIssues = true;
      totalIssues++;
    }
  }

  // Windows path adjustments for string matching in JS array
  const relativePathUnix = relativePath.replace(/\\/g, '/');

  // 1. Check for missing Layout Wrappers in pages (unix path fallback)
  if (relativePathUnix.includes('/app/') && relativePathUnix.endsWith('page.tsx') && !fileHasIssues) {
    const hasLayout = /ExplorerLayout|ScrapbookLayout|CommandCenterLayout|FocusLayout/.test(content);
    // Ignore layout.tsx, error.tsx, loading.tsx, etc.
    if (!hasLayout && !relativePathUnix.includes('api/') && !relativePathUnix.includes('layout.tsx') && !relativePathUnix.includes('not-found.tsx') && !relativePathUnix.includes('error.tsx')) {
      pagesWithoutLayouts.push(relativePathUnix);
      fileHasIssues = true;
      totalIssues++;
    }
  }

  // 2. Check Banned Patterns
  for (const pattern of BANNED_PATTERNS) {
    const matches = content.match(pattern.regex);
    if (matches) {
      fileIssues.push(`**${matches.length}x** ${pattern.name}`);
      fileHasIssues = true;
      totalIssues++;
    }
  }
  
  // 3. Check for raw HTML tables
  if (/<table\b/.test(content) && !/import.*?Table.*?from.*?(ui|shadcn)/.test(content)) {
      fileIssues.push('Raw HTML <table> used instead of shadcn');
      fileHasIssues = true;
      totalIssues++;
  }

  if (fileIssues.length > 0) {
    componentViolations.push(`- [ ] **${relativePathUnix}**: ${fileIssues.join(', ')}`);
  }
}

console.log("🔍 Scanning codebase for UI/UX violations...");

// Ensure workflows dir exists
const workflowDir = path.join(__dirname, '../.agents/workflows');
if (!fs.existsSync(workflowDir)) {
  fs.mkdirSync(workflowDir, { recursive: true });
}

walkDir(SRC_DIR);

// Build formatted markdown
markdownReport += `## 🚨 Phase 1: Pages Missing Layout Archetypes\n`;
markdownReport += `*These pages need their custom containers removed and wrapped in one of the 4 layout components.*\n\n`;
if (pagesWithoutLayouts.length === 0) markdownReport += `*All pages have layout wrappers!*\n`;
pagesWithoutLayouts.forEach(p => markdownReport += `- [ ] **${p}**\n`);

markdownReport += `\n## 🧹 Phase 2: Component CSS Violations\n`;
markdownReport += `*These files contain legacy inline styles, raw HTML tables, or banned legacy classes.* \n\n`;
componentViolations.forEach(v => markdownReport += `${v}\n`);

fs.writeFileSync(REPORT_PATH, markdownReport);
console.log(`\n🏁 Scan complete. Total violations found: ${totalIssues}`);
console.log(`Dossier saved to ${REPORT_PATH}`);
